# Use the official Node.js image as the base image for backend
FROM node:14 AS backend

# Set the working directory inside the container
WORKDIR /app

# Copy the package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the backend files to the working directory
COPY . .

# Start the backend server
CMD ["npm", "start"]
